name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python lint errors
        flake8 --count --show-source --statistics --ignore=E701,E401,E704,F403 --max-line-length=120 --exclude=__init__.py,env/,setup.py
    - name: Test with pytest
      run: |
        python -m pytest
    - name: Build
      run: |
        python -m build
